export const EVENT_TYPES = {
  TREATMENT_COMPLETED: "TREATMENT_COMPLETED",
  APPOINTMENT: "APPOINTMENT",
  BOOKING: "BOOKING",
  BOOKED: "BOOKED",
} as const;

export const EVENT_PATTERNS = {
  APPOINTMENT: "APPOINTMENT",
  BOOKING: "BOOKING",
  BOOKED: "BOOKED",
} as const;
